### ISSUE TITLE
box and measure mean?

### ISSUE THREAD

**Issue by T8354HQ** [ZhangPHEngr/Kalman-in-MOT#1]
Can you have brief saying on how your code is working?
There are box and measure transfers in you utils and others (2 namely ) are build on this

**Comment by ZhangPHEngr** [comment]
> Can you have brief saying on how your code is working? There are box and measure transfers in you utils and others (2 namely ) are build on this

**Comment by ZhangPHEngr** [comment]
sorry for confusing you...
The entry of the project for running code correctly is in main.py, and you can just run "python3 main.py" in terminal or other regular python running methods.
The entry of utils.py and measure.py are convenient for testing function
